config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get '/profil', to: 'users#show', as: :profil
  resources :users, only: [:show]

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  root 'home#index'
  resources :appointments do
    collection do
    get 'me'
    end
  end
  resources :properties do
    resources :comments
  end
  get 'contact' => 'home#contact'
  resources :home, only: [:index, :new, :create]
  post 'guest', to: 'home#guest_user', as: 'guest_user'
  post 'admin', to: 'home#guest_admin', as: 'guest_admin'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :property
  belongs_to :user
  validates :content, presence: true, length: {minimum:1}
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_property, only: [:create, :edit, :update]
  # before_action :set_comment, only: [:edit, :update]
  
  def create
    @comments = Comment.where(property_id: @property).order("created_at DESC")
    # Search Property from the parameter value and build it as comments associated with Property.
    @comment = @property.comments.build(comment_params)
    @comment.user_id = current_user.id
    
    # Change format according to client request
    respond_to do |format|
      if @comment.save
        flash[:succes] = t("comments.created")
        format.html { redirect_to property_path(@property) }
        format.js { render :index }
        # format.json { render :show, status: :created, location: [@servicerequest, @upload] }
      else
        flash[:danger] = 'Could not post...'
        format.html { redirect_to property_path(@property) }
      end
    end
  end

  def edit
    @comment = @property.comments.find(params[:id])
    respond_to do |format|
      flash.now[:notice] = 'Editing comment'
      format.js { render :edit }
    end
  end

  def update
    @comment = @property.comments.find(params[:id])
      respond_to do |format|
        if @comment.update(comment_params)
          flash.now[:notice] = t("comments.updated")
          format.js { render :index }
        else
          flash.now[:notice] = 'Failed to edit comment'
          format.js { render :edit_error }
        end
      end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comments = Comment.where(property_id: @property).order("created_at DESC")
    @comment.destroy
    respond_to do |format|
      #flash[:danger] = 'Comment was successfully destroyed.'
      format.html { redirect_to property_path(@property) }
      format.js { render :index }
    end
    # @comment = Comment.find(params[:id])
    # @comment.destroy
    # respond_to do |format|
    #   flash.now[:notice] = 'Comment deleted'
    #   format.js { render :index }
    # end
  end
  

  private
  # Strong parameters
  def comment_params
    params.require(:comment).permit(:property_id, :user_id, :content)
  end
  def set_property
    @property = Property.find(params[:property_id])
  end
  # def set_comment
  #   @comment = @property.comments.find(params[:id])
  # end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_edit.html.erb
<%= simple_form_for([@property, @comment], remote: true) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :content,
                  autofocus: true ,
                  id: "comment_content_#{property.id}" %>
  </div>

  <div class="actions">
    <%= f.button :submit, class:"btn btn-primary mt-2" %>
  </div>
  
<% end %>

app/views/comments/_form.html.erb
<%= simple_form_for([@property, @comment || @property.comments.build], remote: true) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :content, placeholder: 'Ecrivez ici ce que vous pensez de cette propriété', autofocus: true %>
    <%# <%= f.text_field :content, autofocus: true %>

  </div>

  <div class="form-actions", style="padding-top:20px; padding-bottom:20px;">
      <%= button_to ( f.object.new_record? ? t("button.create_comment") : t("button.update_comment") ), property_comments_path(property_id: @property), remote: true,
       class: 'btn btn-primary'  %>
    </div>
<% end %>

app/views/comments/_index.html.erb
<% comments.each do |comment| %>
  <div class="feed-element">
    <div class="media-body" style="font-size:14px;">
      <% if comment.id.present? %>  
        <div class="well" style="font-size:14px;">
          <div class="comment-content" id ="this_comment_<%= comment.id %>">
            <span class="pull-right text-navy"><%= time_ago_in_words(comment.created_at) %> ago</span>
            <strong><%= comment.user.username %></strong> commented this property.
              <br>
            <strong><%= t("comments.content") %> : </strong><%= comment.content %>
          </div>
          <% if current_user.username == comment.user.username %>
            <div class="actions mt-2">
              <%= link_to t("button.edit"), edit_property_comment_path(property, comment), remote: true, class: 'btn btn-xs btn-primary'  %>
              <%= link_to t("button.destroy"), property_comment_path(comment.property_id, comment.id), method: :delete, remote: true,  data: { confirm: 'Do you really want to delete this?' }, class: 'btn btn-xs btn-outline-danger'  %>
            </div>
          <% end %>
        </div> <br>
      <% end %>
    </div>
  </div>
<% end %>

app/views/comments/destroy.js.erb
$('#comment_<%= @comment.id %>').remove();

app/views/comments/edit.js.erb
$("#this_comment_<%= @comment.id %>").replaceWith("<%= j render 'comments/edit', property: @property, comment: @comment %>");
$("#notice").html("<%= j flash[:notice] %>");

app/views/comments/index.js.erb
$("#comments_area").html("<%= j(render 'comments/index', { comments: @comment.property.comments, property: @comment.property }) %>");
$("textarea").val('');
$("#notice").html("<%= j flash[:notice] %>");