config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get '/profil', to: 'users#show', as: :profil
  resources :users, only: [:show]

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  root 'home#index'
  resources :appointments do
    collection do
    get 'me'
    end
  end
  resources :properties do
    resources :comments
  end
  get 'contact' => 'home#contact'
  resources :home, only: [:index, :new, :create]
  post 'guest', to: 'home#guest_user', as: 'guest_user'
  post 'admin', to: 'home#guest_admin', as: 'guest_admin'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/partials/_footer.html.erb
<footer class="bg-primary text-white mt-3">
    <div class="text-center p-3">
        © Dive into code ~ Octobre 2021 Copyright: <a class="text-white" href="http://bit.ly/EmiG">About Me</a>
    </div>
</footer>

app/views/partials/_home.html copy.erb
<header class="p-2 bg-primary text-white fixed-top ">
    <div class="container-fluid row d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
     
        <div class="col-3">
            <a href="/" class="navbar-brand mb-2 mb-lg-0 text-white"><span class="fb"><%= t("button.brand") %></span></a>
        </div>
        
        <div class=" col-9">
            <% if user_signed_in? %> 
              <div class="row">
                <div class="col-7 ">
                  <div class="form-group d-flex justify-content-center mb-2 mb-lg-0 ">
                    <a href="<%= properties_path %>" class="btn btn-warning me-5 ml-5" role="button"><%= t("button.properties_list") %></a>
                    <% if current_user.is_admin %>
                      <a href="<%= appointments_path %>" class="btn btn-success me-5 " role="button"><%= t("button.appointments") %></a>
                    <% else %>
                      <a href="<%= me_appointments_path %>" class="btn btn-success me-5 " role="button"><%= t("button.my_appointments") %></a>
                    <% end %>
                    <% if current_user.is_admin %>
                      <a href="<%= rails_admin_path %>" class="btn btn-info ml-2 " role="button">Management</a>
                    <% end %>
                  </div>  
                </div>
                <div class=" col-5  text-end text-decoration-none">
                <a class ="btn btn-info" href="<%= contact_path %>" role="button"><%= t("button.contact_us") %></a>
                  <%= link_to "Profile", profil_path, class:"btn btn-success me-2" %>
                  <%= link_to t("button.log_out"), destroy_user_session_path, method: :delete, class:"btn btn-danger" %>
                </div> 
            <% else %>
              <div class="col-12 text-end text-decoration-none">
                <%= link_to t("button.admin"), guest_admin_path, method: :post, class: " me-2 btn btn-success "%>
                <%= link_to t("button.guest"), guest_user_path, method: :post, class: " me-2 btn btn-info "%>
                <a class="btn btn-success me-2" href="<%= new_user_session_path %>" role="button"><%= t("button.log_in") %></a>
                <a class="btn btn-warning me-2" href="<%= new_user_registration_path %>" role="button"><%= t("button.sign_up") %></a>
                <a class ="btn btn-info" href="<%= contact_path %>" role="button"><%= t("button.contact_us") %></a>
                
              </div> 
              </div>
            <% end %>
        </div> 
    </div>
</header>

app/views/partials/_home.html.erb
<header class="p-2 bg-primary text-white fixed-top ">
    <div class="container-fluid row d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
     
        <div class="col-3">
            <a href="/" class="navbar-brand mb-2 mb-lg-0 text-white"><span class="fb"><%= t("button.brand") %></span></a>
        </div>
        
        <div class=" col-9">
            <% if user_signed_in? %> 
              <div class="row">
                <div class="col-7 ">
                  <div class="form-group d-flex justify-content-center mb-2 mb-lg-0 ">
                    <a href="<%= properties_path %>" class="btn btn-warning me-5 ml-5" role="button"><%= t("button.properties_list") %></a>
                    <% if current_user.is_admin %>
                      <a href="<%= appointments_path %>" class="btn btn-success me-5 " role="button"><%= t("button.appointments") %></a>
                    <% else %>
                      <a href="<%= me_appointments_path %>" class="btn btn-success me-5 " role="button"><%= t("button.my_appointments") %></a>
                    <% end %>
                    <% if current_user.is_admin %>
                      <a href="<%= rails_admin_path %>" class="btn btn-info ml-2 " role="button">Management</a>
                    <% end %>
                  </div>  
                </div>
                <div class=" col-5  text-end text-decoration-none">
                <a class ="btn btn-info" href="<%= contact_path %>" role="button"><%= t("button.contact_us") %></a>
                  <%= link_to "Profile", profil_path, class:"btn btn-success me-2" %>
                  <%= link_to t("button.log_out"), destroy_user_session_path, method: :delete, class:"btn btn-danger" %>
                </div> 
            <% else %>
              <div class="col-12 text-end text-decoration-none">
                <%= link_to t("button.admin"), guest_admin_path, method: :post, class: " me-2 btn btn-success "%>
                <%= link_to t("button.guest"), guest_user_path, method: :post, class: " me-2 btn btn-info "%>
                <a class="btn btn-success me-2" href="<%= new_user_session_path %>" role="button"><%= t("button.log_in") %></a>
                <a class="btn btn-warning me-2" href="<%= new_user_registration_path %>" role="button"><%= t("button.sign_up") %></a>
                <a class ="btn btn-info" href="<%= contact_path %>" role="button"><%= t("button.contact_us") %></a>
                
              </div> 
              </div>
            <% end %>
        </div> 
    </div>
</header>