config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get '/profil', to: 'users#show', as: :profil
  resources :users, only: [:show]

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  root 'home#index'
  resources :appointments do
    collection do
    get 'me'
    end
  end
  resources :properties do
    resources :comments
  end
  get 'contact' => 'home#contact'
  resources :home, only: [:index, :new, :create]
  post 'guest', to: 'home#guest_user', as: 'guest_user'
  post 'admin', to: 'home#guest_admin', as: 'guest_admin'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/property.rb
class Property < ApplicationRecord
  mount_uploaders :images, ImageUploader
  paginates_per 5
  belongs_to :user, optional: true
  has_many :comments, dependent: :destroy
  has_many_attached :images
  #accepts_nested_attributes_for :images, reject_if: :all_blank, allow_destroy: true
  validates :name, presence:true, length: {minimum:1, maximum:30}
  validates :description, presence: true
  validates :price, presence: true
  validates :address, presence: true
  validates :type_of_property, presence: true
  validates :status, presence: true
  validate :image_type

  # def thumbnail input
  #   return self.images[input].variant(resize: '500*500!').processed
  # end

  scope :type_of_property_search, -> (query) {where("type_of_property LIKE ?", "%#{query}%")}
    def type_of_property_search(query)
      where("type_of_property LIKE ?", "%#{query}%")
    end

	scope :status_search, -> (query) {where(status: query)}
    def status_search(query)
      where(status: query)
    end

  private
  def image_type
    images.each do |image|
      if !image.content_type.in?(%('image/jpeg image/png '))
        errors.add(:images, 'needs to be JPEG or PNG')
      end
    end
  end
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  load_and_authorize_resource

  # GET /properties or /properties.json
  def index
    # @properties = current_user.properties.order(created_at: :desc).page(params[:page]).includes(:user)
    @properties = Property.order(created_at: :desc).page(params[:page])
    @properties = Property.order(type_of_property: :asc).page(params[:page]).includes(:user) if params[:sort_type]
    @properties = Property.order(status: :asc).page(params[:page]).includes(:user) if params[:sort_status]


    if params[:type_of_property].present?
			if params[:status].present? 
				@properties = Property.type_of_property_search(params[:type_of_property]).status_search(params[:status]).page params[:page]
			else
				@properties = Property.type_of_property_search(params[:type_of_property]).page(params[:page])
			end
		else
      if params[:status].present?
			  @properties = Property.status_search(params[:status]).page(params[:page])
      end
		end

  end

  # GET /properties/1 or /properties/1.json
  def show
    @comments = @property.comments
    @comment = @property.comments.build
    # @images = @property.images.all
  end

  # GET /properties/new
  def new
    @property = Property.new
    # @image = @property.images.build
    # @property.images.build
    
  end

  # GET /properties/1/edit
  def edit
    # @images = @property.images.build
  end

  # POST /properties or /properties.json
  def create

    @property = current_user.properties.build(property_params)
    # property.images.attach(params[:property][:images])
    respond_to do |format|
      if @property.save
        # params[:images]['illustration'].each do |a|
        #     @image = @property.images.create!(:illustration => a, :property_id => @property.id, :title => @title)
        # end
        # params[:property][:images].each do |a|
        #   @property = @property.images.create!(:images =>a)
        # end
          flash[:success] = t("properties.created")
          format.html { redirect_to @property }
          format.js { render :index }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.js { render :index }
      end
    end

  end

  # PATCH/PUT /properties/1 or /properties/1.json
  def update
    respond_to do |format|
      if @property.update(property_params)
        flash[:success] = t("properties.updated") 
        format.html { redirect_to @property }
        format.json { render :show, status: :ok, location: @property }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /properties/1 or /properties/1.json
  def destroy
    @property.destroy
    respond_to do |format|
      flash[:danger] = t("properties.destroyed")
      format.html { redirect_to properties_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    # def set_property
    #   @property = Property.find(params[:id])
    # end

    # Only allow a list of trusted parameters through.
    def property_params
      params.require(:property).permit(:name, :type_of_property, :description, :address, :price, :status, images: [])
    end
end

app/helpers/properties_helper.rb
module PropertiesHelper
    def new_or_create_not_edit
        if action_name == 'new' || action_name == 'create'
          confirm_properties_path
        elsif action_name == 'edit'
          property_path
        end
      end
end

app/views/properties/Copies/index.html copy.erb
<p id="notice"><%= notice %></p>

<div class="container text-center">
  <h1>Properties List</h1><br>
  <div class ='table-responsive '>
   <div class="d-flex">
      <div class=" mr-5">
        <a href = "<%= properties_path(sort_expired: "true") %>" class="btn btn-primary">Sort by end deadline</a>
      </div>
      <div class="">
        <a href = "<%= properties_path(sort_priority: "true") %>" class="btn btn-primary">Sort by priority </a>
      </div>
  </div> <br>


 <table class = "table table-striped table-hover border" >
  <thead>
    <tr>
      <th>Name</th>
      <th>Type of property</th>
      <th>Description</th>
      <th>Illustration</th>
      <th>Address</th>
      <th>Price</th>
      <th>Status</th>
      <th>Posted by</th>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @properties.each do |property| %>
      <tr>
        <td><%= property.name %></td>
        <td class="type_row"><%= property.type_of_property %></td>
        <td><%= truncate(property.description , length: 50) %></td>
        <td><%= property.illustration %></td>
        <td><%= property.address %></td>
        <td><%= property.price %></td>
        <td class="status_row"><%= property.status %></td>
        <td><%= property.user.username %></td>
        <td>
          <%= link_to 'Show', property %>
          <%= link_to 'Edit', edit_property_path(property) %>
          <%= link_to 'Destroy', property, method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Property', new_property_path %>
<div class="container pagination justify-content-center" >
    <%= paginate @properties, theme: 'twitter-bootstrap-4', pagination_class: "pagination-sm" %>
</div>

// <td>
//     <a href = "<%= task_path(task.id) %>" class="btn btn-primary">Show</a>
//     <a href = "<%= edit_task_path(task.id) %>" class="btn btn-warning">Edit</a>
//     <a href = "<%= task_path(task.id) %>" class="btn btn-danger", data-confirm="Are you sure?" data-method="DELETE">Destroy</a>
// </td>
  

app/views/properties/Copies/show.html copy 2.erb
<p>
  <strong>Illustration:</strong>
  <%= @property.illustration %>
</p>
<p>
  <strong>Name:</strong>
  <%= @property.name %>
</p>

<p>
  <strong>Type of property:</strong>
  <%= @property.type_of_property %>
</p>

<p>
  <strong>Description:</strong>
  <%= @property.description %>
</p>

<p>
  <strong>Address:</strong>
  <%= @property.address %>
</p>

<p>
  <strong>Price:</strong>
  <%= @property.price %> FCFA
</p>

<p>
  <strong>Status:</strong>
  <%= @property.status %>
</p>

<p>
  <strong>User:</strong>
  <%= @property.user.username %>
</p>

<%= link_to 'Edit', edit_property_path(@property) %> |
<%= link_to 'Back', properties_path %>


<div class="d-flex flex-column container justify-content-center align-itmes-center" style = "padding-top: 1rem;">

      <div class="d-flex flex-column justify-content-center align-itmes-center card text-center" style=""> <br>
        <div class="card-img-top">
            <%= image_tag(@property.illustration.url) if @property.illustration.url%>
        </div>
        <div class="card-body">
            <p class="card-text text-justify"><%= @property.description %></p>
        </div><br>
        <blockquote class="blockquote mb-0">
          <footer class="blockquote-footer">
            Posté par : <cite title="Source Title"><%= @property.user.name %></cite>
          </footer> 
        </blockquote>
      </div>

      <div class="d-flex flex-row justify-content-center align-itmes-center form-actions mb-4"> 
        <% if @property.user == current_user %>
            <a class="btn btn-warning w-25 m-4" href = "<%= edit_property_path(@property)%>">Modifier</a> 
        <% end %>
            <a class="btn btn-primary w-25 m-4" href = "<%= propertys_path %>"> Publications</a>        
      </div>
</div> <br> <br><br>

app/views/properties/Copies/show.html copy 3.erb
<p id="notice"><%= notice %></p>


<p>
  <strong>Illustration:</strong>
  <%= @property.illustration %>
</p>
<p>
  <strong>Name:</strong>
  <%= @property.name %>
</p>

<p>
  <strong>Type of property:</strong>
  <%= @property.type_of_property %>
</p>

<p>
  <strong>Description:</strong>
  <%= @property.description %>
</p>

<p>
  <strong>Address:</strong>
  <%= @property.address %>
</p>

<p>
  <strong>Price:</strong>
  <%= @property.price %> FCFA
</p>

<p>
  <strong>Status:</strong>
  <%= @property.status %>
</p>

<p>
  <strong>User:</strong>
  <%= @property.user.username %>
</p>

<%= link_to 'Edit', edit_property_path(@property) %> |
<%= link_to 'Back', properties_path %>
<%= f.input :address, as: :string, input_html: {class: 'form-datepicker'} %>
 <% if @comment.user == current_user %>
          <p><%= link_to "Edit comment", edit_property_comment_path(property, comment), remote: true %></p>
          <p><%= link_to "Delete comment", property_comment_path(comment.property_id, comment.id), method: :delete, remote: true, data: { confirm: "Do you really want to delete this?"} %></p>
        <% end %>

app/views/properties/Copies/show.html copy.erb
<p>
  <strong>Illustration:</strong>
  <%= @property.illustration %>
</p>
<p><strong>Name:</strong><%= @property.name %></p>

<p><strong>Type of property:</strong><%= @property.type_of_property %></p>

<p><strong>Description:</strong><%= @property.description %></p>

<p><strong>Address:</strong><%= @property.address %></p>

<p><strong>Price:</strong><%= @property.price %> FCFA</p>

<p><strong>Status:</strong><%= @property.status %></p>

<p><strong>User:</strong><%= @property.user.username %></p>

<div class="card-img-top">
      
     <%= @property.images.each do |image| %>
      <%= image_tag(image) %>
    <% end %>
    <%= @property.images.each do |image| %>
      <%= image_tag(image) %>
    <% end %>
    
    </div>
    <%= (0...@property.images.count).each do |image| %>
      <%= image_tag(@property.images[image], style: "max-width: 1000px; max-height: 1000px") %>
    <% end %>

      <hr />
  <p>List of comments </p>
  <!-- Get the HTML id of this comments_area and update only that part of the div-->
  <div id="comments_area">
    <!-- Render to display a list of posted comments on the property details page -->
    <%= render partial: 'comments/index', locals: { comments: @comments, property: @property, user: @user } %>
  </div>
  <!-- Render to display the comment input field on the detail page of the property -->
  <%= render partial: 'comments/form', locals: { comment: @comment, property: @property } %>

  <% if @property.user == current_user %>
    <a class="btn btn-danger w-25 m-4" href = "<%= edit_property_path(@property)%>">Edit</a> 
  <% end %>|
<%= link_to 'Back', properties_path %>

</div> <br> <br><br>