config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get '/profil', to: 'users#show', as: :profil
  resources :users, only: [:show]

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  root 'home#index'
  resources :appointments do
    collection do
    get 'me'
    end
  end
  resources :properties do
    resources :comments
  end
  get 'contact' => 'home#contact'
  resources :home, only: [:index, :new, :create]
  post 'guest', to: 'home#guest_user', as: 'guest_user'
  post 'admin', to: 'home#guest_admin', as: 'guest_admin'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  paginates_per 5
  belongs_to :user, optional: true
  validates :description, presence:true, length: {minimum:1, maximum:50}
  # validates :date, presence:true

  validates :date,
  :date => { :after => Time.now + 1.hour, :before => Time.now + 1.year }
end
# <div data-l="fr" class="wgcurrent wg-li fr"><a tabindex="-1" href="#" target="_self" role="none" id="weglot-language-fr">Français</a></div>

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
load_and_authorize_resource

  # GET /appointments or /appointments.json
  def index
    @appointments = Appointment.order(created_at: :desc).page(params[:page])
  end

  def me
    @appointments = current_user.appointments.order(created_at: :desc).page(params[:page]).includes(:user)
    render :index
  end

  # GET /appointments/1 or /appointments/1.json
  def show
  end

  # GET /appointments/new
  def new
    @appointment = Appointment.new
  end

  # GET /appointments/1/edit
  def edit
  end

  # POST /appointments or /appointments.json
  def create
    @appointment = current_user.appointments.build(appointment_params)

    respond_to do |format|
      if @appointment.save
        AppointmentMailer.appointment_mailer(current_user).deliver
        flash[:success] = t("appointments.created")
        format.html { redirect_to @appointment }
        format.json { render :show, status: :created, location: @appointment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /appointments/1 or /appointments/1.json
  def update
    respond_to do |format|
      if @appointment.update(appointment_params)

        flash[:success] = t("appointments.updated")
        format.html { redirect_to @appointment }
        format.json { render :show, status: :ok, location: @appointment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /appointments/1 or /appointments/1.json
  def destroy
    @appointment.destroy
    respond_to do |format|
      flash[:danger] = t("appointments.destroyed")
      format.html { redirect_to appointments_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    # def set_appointment
    #   @appointment = Appointment.find(params[:id])
    # end

    # Only allow a list of trusted parameters through.
    def appointment_params
      params.require(:appointment).permit(:description, :status, :date)
    end
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/views/appointments/_form.html.erb
<%= simple_form_for(@appointment) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <div class="form-group mt-3 mb-3">
      <%= f.input :description, placeholder: "L'objet de votre demande de rendez-vous", autofocus: true %>
    </div>

    <div class="form-group mt-3 mb-3">
      <%= f.input :status, :collection => ["Low", "Medium", "High"],:input_html => { :class => 'form-control'}, prompt: "Choose From List" %>
    </div>
    <div class="form-group mt-3 mb-3">
      <%= f.input :date, id: "date", class: "" %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class:"btn btn-success mb-2 w-100"  %>
  </div>
<% end %>

app/views/appointments/edit.html.erb
<br> 
<div class="w-25 mt-5 d-flex flex-column container justify-content-center align-itmes-center" style = "padding-top: 1rem; border: 1px solid;">
<h1><%= t("appointments.edit") %></h1>

<%= render 'form', appointment: @appointment %>

<%= link_to t("button.show"), @appointment, class:"btn btn-info mb-2" %>
<% if current_user.is_admin %>
    <a href = "<%= appointments_path %>" class="btn btn-success mb-2"><%= t("button.back") %></a>
<% else %>
    <a href="<%= me_appointments_path %>" class="btn btn-warning mb-2" role="button"><%= t("button.back") %></a>
<% end %>
</div>

app/views/appointments/index.html.erb
<br>
<div class="container text-center mt-5">
  <h1><%= t("appointments.title")  %></h1><br>

  <div class ='table-responsive'>
    <div class="">
      <a href = "<%= new_appointment_path  %>" class="btn btn-primary"><%= t("appointments.add") %></a>
    </div> <br >


    <table class = "table table-striped table-hover border" >
      <thead class="thead-dark">
        <tr>
          <th>Description</th>
          <th><%= t("properties.status") %></th>
          <th>Date</th>
          <th><%= t("appointments.requested_by") %></th>
          <th><%= t("appointments.confirmed") %></th>
          <th>Actions</th>
        </tr>
      </thead>

      <tbody>
        <% @appointments.each do |appointment| %>
          <tr>
            <td><%= truncate(appointment.description , length: 20) %></td>
            <td><%= appointment.status if appointment.status %></td>
            
            <td><%= appointment.date.strftime("%d %b %Y à %H:%M") if appointment.date %></td>
            <td><%= appointment.user.username %></td>
            <td class="table-info">
              <% if appointment.confirmed %>
                  <h5> <span class="badge">Yes</span></h5>
              <% else %>
                 <h5 class="badge">En étude</h5>
              <% end%>
            </td>
            <td class="d-flex">
              <a href = "<%= appointment_path(appointment.id) %>" class="btn btn-primary me-2"><%= t("button.show") %></a>
              <a href = "<%= edit_appointment_path(appointment) %>" class="btn btn-warning me-2"><%= t("button.edit") %></a>
              <a href = "<%= appointment_path(appointment.id) %>" class="btn btn-danger", data-confirm="Are you sure?" data-method="DELETE"><%= t("button.delete") %></a>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <div class="mt-2 container pagination justify-content-center" >
      <%= paginate @appointments, theme: 'twitter-bootstrap-4', pagination_class: "pagination-sm" %>
  </div>
</div>

app/views/appointments/new.html.erb
 <br> 
<div class="w-25 mt-5 d-flex flex-column container justify-content-center align-itmes-center" style = "padding-top: 1rem; border: 1px solid;">

<h1><%= t("appointments.new") %></h1>

<%= render 'form', appointment: @appointment %>
<% if current_user.is_admin %>
    <a href = "<%= appointments_path %>" class="btn btn-success mb-2"><%= t("button.back") %></a>
<% else %>
    <a href="<%= me_appointments_path %>" class="btn btn-warning mb-2" role="button"><%= t("button.back") %></a>
<% end %>

</div>

app/views/appointments/show.html.erb
<br>  <br>
<div class="w-25 mt-5 mb-4 d-flex flex-column container justify-content-center align-itmes-center" style = "padding-top: 1rem; border: 1px solid;">
    <h1><%= t("appointments.details") %></h1> <hr />
    <p><strong>Description:  </strong><%= @appointment.description %></p>

    <p><strong><%= t("properties.status") %>  : </strong><%= @appointment.status if @appointment.status %></p>

    <p><strong>Date:  </strong><%= @appointment.date.strftime("%d %b %Y à %H:%M") if @appointment.date %></p>

    <p><strong><%= t("appointments.requested_by") %> :   </strong><%= @appointment.user.username %></p>
    <a href = "<%= edit_appointment_path(@appointment) %>" class="btn btn-warning mb-2"><%= t("button.edit") %></a>
    <% if current_user.is_admin %>
        <a href = "<%= appointments_path %>" class="btn btn-success mb-2"><%= t("button.back") %></a>
     <% else %>
        <a href="<%= me_appointments_path %>" class="btn btn-success mb-2" role="button"><%= t("button.back") %></a>
     <% end %>

</div> <br>